import car01 from "../images/car-01.png";

const ParkingAll = [
  {
    id: "01",
    carName: "Colombo City Moll",
    category: "A",
    type: "Manual",
    groupSize: 4,
    rentPrice: 89,
    imgUrl: car01,
  },
  {
    id: "02",
    carName: "Viharamaha devi park",
    category: "A",
    type: "Manual",
    groupSize: 4,
    rentPrice: 59,
    imgUrl: car01,
  },
  {
    id: "03",
    carName: "Asiri Hospital",
    category: "B",
    type: "Manual",
    groupSize: 80,
    rentPrice: 109,
    imgUrl: car01,
  },
  {
    id: "04",
    carName: "Genaral Hospital",
    category: "C ",
    type: "Manual",
    groupSize: 4,
    rentPrice: 99,
    imgUrl: car01,
  },
  {
    id: "05",
    carName: "One Gall face mall",
    category: "B ",
    type: "Manual",
    groupSize: 4,
    rentPrice: 109,
    imgUrl: car01,
  },
  {
    id: "06",
    carName: "Main Car park",
    category: "A",
    type: "Manual",
    groupSize: 4,
    rentPrice: 89,
    imgUrl: car01,
  },
  {
    id: "07",
    carName: "Main Car park 2",
    category: "A ",
    type: "Manual",
    groupSize: 4,
    rentPrice: 89,
    imgUrl: car01,
  },
  {
    id: "08",
    carName: "Main Car park 3",
    category: "B ",
    type: "Manual",
    groupSize: 4,
    rentPrice: 59,
    imgUrl: car01,
  },
  {
    id: "09",
    carName: "Main Car park 4 ",
    category: "B",
    type: "Manual",
    groupSize: 4,
    rentPrice: 109,
    imgUrl: car01,
  },
  {
    id: "10",
    carName: "Main Car park 2",
    category: "A ",
    type: "Manual",
    groupSize: 4,
    rentPrice: 89,
    imgUrl: car01,
  },
  {
    id: "11",
    carName: "Main Car park 3",
    category: "B ",
    type: "Manual",
    groupSize: 4,
    rentPrice: 59,
    imgUrl: car01,
  },
  {
    id: "12",
    carName: "Main Car park 4 ",
    category: "B",
    type: "Manual",
    groupSize: 4,
    rentPrice: 109,
    imgUrl: car01,
  },
];

export default ParkingAll;